---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 10080}]
  driver_config:
    ### Example of how to pull down a privately hosted box
    # box: windows2008r2
    # box_url: http://repo.company.com/virtualboxes/windows2008r2.box

    # Set the proxy used by Vagrant to download boxes
    http_proxy: <%= ENV['http_proxy'] %>
    https_proxy: <%= ENV['https_proxy'] %>

provisioner:
  name: chef_zero
  always_update_cookbooks: true

  # Set the proxy used inside the VM to download chef-client
  http_proxy: <%= ENV['http_proxy'] %>
  https_proxy: <%= ENV['https_proxy'] %>

verifier:
  name: inspec

platforms:
  - name: centos-7.2
  ### This would spin up the privately hosted Windows box
  # - name: windows2008r2

suites:
  - name: default
    run_list:
      - recipe[test-kitchen-demo::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      chef-client:
        config:
          # Allow chef-client to access the proxy during converge
          http_proxy: <%= ENV['http_proxy'] %>
          https_proxy: <%= ENV['http_proxy'] %>
